name = "GrowthModels"
uuid = "47660a32-d12f-45a8-8e9e-9bf97893ab41"
authors = ["Ed Jee <edjee96@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
